### ISSUE TITLE
Effect Idea: Isekai'd - Spawns a truck in front of you, ramming into you with high speed

### ISSUE THREAD

**Issue by Edelgaspirat** [berkayylmao/NFS-Chat-Chaos-Mod#10]

**Comment by berkayylmao** [comment]
Already implemented in chaos mod ->

<html>
<body>


95 | Pepega Truck | Did you think he forgot about you? | true | 10
-- | -- | -- | -- | --


<br class="Apple-interchange-newline">
</body>
</html>
