### ISSUE TITLE
[suggestion] add categories to similar effects

### ISSUE THREAD

**Issue by 0rangeGhost** [berkayylmao/NFS-Chat-Chaos-Mod#3]
would be nice to make categories for similar effects, like changing car sizes (wide, long, tall etc), like in gtav chaos mod, so similar effects count as one and doesn't show up so often

**Comment by berkayylmao** [comment]
Possibly fixed with 760aa5ebf83559a39f9cbe62fb1dad1e1e49526f and 0719fd0e30ff16077fc71fc78847ae68518a41eb. Cooldowns of the effects are now generated from a seed.

**Comment by berkayylmao** [comment]
Patch implemented in [v1.6.0](https://github.com/berkayylmao/NFS-Chat-Chaos-Mod/releases/latest). Please post an update on the issue when you can.

**Comment by 0rangeGhost** [comment]
i guess it feels less anoying, or i just got used to such effects :D

**Comment by berkayylmao** [comment]
Ok, then I'm closing this issue since cooldowns are pure random now.
