### ISSUE TITLE
keyboard player effect doesn't work

### ISSUE THREAD

**Issue by 0rangeGhost** [berkayylmao/NFS-Chat-Chaos-Mod#6]
when effect occured - i was just stuck on throttle and couldn't do anything, and after effect ended - controls were messed up and game crashed shortly.
https://youtu.be/vkMd6_5BuY4
after i rewatched clip - i think it just enabled inputs permanently, so when i released keys - inputs were still on.
also, other effects which affect controls - they are just freeze controls. like when disable brakes effect happens, if you were pressing brakes - you will stuck on brakes untill effect ends

**Comment by berkayylmao** [comment]
Patch implemented in [v1.6.1](https://github.com/berkayylmao/NFS-Chat-Chaos-Mod/releases/latest). Please post an update on the issue when you can.
